// Generated by CoffeeScript 1.3.3
(function() {
  var bacboneSync, methodMap;

  bacboneSync = Backbone.sync;

  methodMap = {
    'create': 'POST',
    'update': 'PUT',
    'patch': 'PATCH',
    'delete': 'DELETE',
    'read': 'GET'
  };

  Backbone.sync = function(method, model, options) {
    var type, xhr;
    type = methodMap[method];
    xhr = bacboneSync(method, model, options);
    xhr.always(function(data) {
      var locationHeader, matches, regex;
      regex = /([\dA-z]+)/g;
      console.log(_.result(model, 'url'));
      matches = _.result(model, 'url').match(regex);
      console.log(matches);
      if (matches != null ? matches.length : void 0) {
        console.log(matches[matches.length - 1]);
      }
      if (model instanceof Backbone.Model) {
        if (type === 'POST' && xhr.status === 201) {
          locationHeader = xhr.getResponseHeader('Location');
          if (locationHeader) {
            regex = /([\dA-z]+)/g;
            matches = locationHeader.match(regex);
            if (matches != null ? matches.length : void 0) {
              model.set('id', matches[matches.length - 1]);
            }
          }
        }
      }
    });
    return xhr;
  };

}).call(this);
