// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone'], function(_, Backbone) {
    var BaseModel, Todo, User;
    BaseModel = (function(_super) {

      __extends(BaseModel, _super);

      BaseModel.prototype._preservedAttributes = {};

      function BaseModel(attributes, options) {
        BaseModel.__super__.constructor.call(this, attributes, options);
        this._preservedAttributes = this.toJSON();
        return;
      }

      BaseModel.prototype.parse = function(response) {
        response = BaseModel.__super__.parse.call(this, response);
        this._preservedAttributes = this.toJSON();
        return response;
      };

      BaseModel.prototype.isDirty = function() {
        return !_.isEqual(this.toJSON(), this._preservedAttributes);
      };

      BaseModel.prototype.set = function(attributes, options) {
        BaseModel.__super__.set.call(this, attributes, options);
        if (this.isValid() === false && !this.has('invalid')) {
          this.set('invalid', this.isValid());
        } else if (this.isValid() === true && this.has('invalid')) {
          this.unset('invalid', {
            silent: true
          });
        }
      };

      return BaseModel;

    })(Backbone.Model);
    User = (function(_super) {

      __extends(User, _super);

      function User() {
        return User.__super__.constructor.apply(this, arguments);
      }

      User.prototype.urlRoot = '/api/users/user';

      User.prototype.defaults = {
        name: '',
        tasksUrl: ''
      };

      User.prototype.updateName = function(newName) {
        return this.set({
          name: newName
        });
      };

      return User;

    })(BaseModel);
    Todo = (function(_super) {

      __extends(Todo, _super);

      function Todo() {
        return Todo.__super__.constructor.apply(this, arguments);
      }

      Todo.prototype.urlRoot = '/api/tasks/task';

      Todo.prototype.defaults = {
        description: '',
        completed: false
      };

      Todo.prototype.updateDescription = function(newDescription) {
        this.set('description', newDescription);
      };

      Todo.prototype.toggle = function() {
        this.save('completed', !this.get('completed'));
      };

      return Todo;

    })(BaseModel);
    return {
      User: User,
      Todo: Todo
    };
  });

}).call(this);
